<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef2232ca8c5ef1f7f1c1dcf1c23a4424
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef2232ca8c5ef1f7f1c1dcf1c23a4424::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef2232ca8c5ef1f7f1c1dcf1c23a4424::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitef2232ca8c5ef1f7f1c1dcf1c23a4424::$classMap;

        }, null, ClassLoader::class);
    }
}
